environment:
  nodejs_version: "7"

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
build: off
test_script:
  - node --version
  - yarn --version
  - yarn lint
  - yarn test
version: "{build}"
